a = None
if a is not None:
    print("har")
else:
    print("dog")

print("aight")
print("aight")
print("aight")
print("aight")
print("aight")
print("aight")
print("aight")
print("aight")
print("aight")
print("aight")
print("aight")
print("aight")
print("aight")
print("aight")
print("aight")
print("aight")
print("aight")
print("aight")
print("aight")
print("aight")
print("aight")
print("aight")
print("aight")
print("aight")
print("aight")
print("aight")
print("aight")
print("aight")
print("aight")
print("aight")
print("aight")
print("aight")
print("aight")
print("aight")
print("aight")
print("aight")
print("aight")
print("aight")
print("aight")
print("aight")
print("aight")
print("aight")
print("aight")
print("test - review pass #2")
print(
    "aight but seriously is that good? It's so small I can barely see it.............................................."
)
print("aight")
